name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_speed_dial: ^7.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - lib/assets/grafik.jpeg
    - lib/assets/avatar.png
    - lib/assets/plastic_codes.jpg
