name: map_hijau
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  animated_card: ^2.0.0
  animations: ^2.0.7
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  flutter_localization: ^0.3.3
  flutter_login: ^5.1.0
  flutter_speed_dial: ^7.0.0
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  local_auth: ^2.3.0
  lottie: ^2.7.0
  permission_handler: ^12.0.1
  provider: ^6.1.5
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4   

flutter:
  uses-material-design: true

  assets:
    - lib/assets/grafik.jpeg
    - lib/assets/avatar.png
    - lib/assets/plastic_codes.jpg
    - lib/assets/tps1.jpg
    - lib/assets/tps2.jpg
    - lib/assets/tps3.jpg
    - lib/assets/chart1.jpeg
    - lib/assets/chart2.jpeg


flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/app_icon.png" 
  adaptive_icon_background: "#43A047"    
  adaptive_icon_foreground: "lib/assets/icon/app_icon.png" 